#!/bin/bash

# Base 16 tomorrow dark colors for gnome-terminal 3.10

base00=#1d1f21
base01=#282a2e
base02=#373b41
base03=#969896
base04=#b4b7b4
base05=#c5c8c6
base06=#e0e0e0
base07=#ffffff
base08=#cc6666
base09=#de935f
base0A=#f0c674
base0B=#b5bd68
base0C=#8abeb7
base0D=#81a2be
base0E=#b294bb
base0F=#a3685a

palette="['$base00','$base08','$base0B','$base0A','$base0D','$base0E','$base0C','$base05','$base03','$base09','$base01','$base02','$base04','$base06','$base0F','$base07']"
foreground_color="'$base05'"
background_color="'$base00'"
bold_color="'$base05'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
