#!/bin/bash

# Base 16 greenscreen dark colors for gnome-terminal 3.10

base00=#001100
base01=#003300
base02=#005500
base03=#007700
base04=#009900
base05=#00bb00
base06=#00dd00
base07=#00ff00
base08=#007700
base09=#009900
base0A=#007700
base0B=#00bb00
base0C=#005500
base0D=#009900
base0E=#00bb00
base0F=#005500

palette="['$base00','$base08','$base0B','$base0A','$base0D','$base0E','$base0C','$base05','$base03','$base09','$base01','$base02','$base04','$base06','$base0F','$base07']"
foreground_color="'$base05'"
background_color="'$base00'"
bold_color="'$base05'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
