#!/bin/bash

# Base 16 mocha dark colors for gnome-terminal 3.10

base00=#3B3228
base01=#534636
base02=#645240
base03=#7e705a
base04=#b8afad
base05=#d0c8c6
base06=#e9e1dd
base07=#f5eeeb
base08=#cb6077
base09=#d28b71
base0A=#f4bc87
base0B=#beb55b
base0C=#7bbda4
base0D=#8ab3b5
base0E=#a89bb9
base0F=#bb9584

palette="['$base00','$base08','$base0B','$base0A','$base0D','$base0E','$base0C','$base05','$base03','$base09','$base01','$base02','$base04','$base06','$base0F','$base07']"
foreground_color="'$base05'"
background_color="'$base00'"
bold_color="'$base05'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
