#!/bin/bash

# Base 16 monokai dark colors for gnome-terminal 3.8.x

base00=#272822
base01=#383830
base02=#49483e
base03=#75715e
base04=#a59f85
base05=#f8f8f2
base06=#f5f4f1
base07=#f9f8f5
base08=#f92672
base09=#fd971f
base0A=#f4bf75
base0B=#a6e22e
base0C=#a1efe4
base0D=#66d9ef
base0E=#ae81ff
base0F=#cc6633

palette="['$base00','$base08','$base0B','$base0A','$base0D','$base0E','$base0C','$base05','$base03','$base09','$base01','$base02','$base04','$base06','$base0F','$base07']"
foreground_color="'$base05'"
background_color="'$base00'"
bold_color="'$base05'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
