#!/bin/bash

# Base 16 railscasts dark colors for gnome-terminal 3.10

base00=#2b2b2b
base01=#272935
base02=#3a4055
base03=#5a647e
base04=#d4cfc9
base05=#e6e1dc
base06=#f4f1ed
base07=#f9f7f3
base08=#da4939
base09=#cc7833
base0A=#ffc66d
base0B=#a5c261
base0C=#519f50
base0D=#6d9cbe
base0E=#b6b3eb
base0F=#bc9458

palette="['$base00','$base08','$base0B','$base0A','$base0D','$base0E','$base0C','$base05','$base03','$base09','$base01','$base02','$base04','$base06','$base0F','$base07']"
foreground_color="'$base05'"
background_color="'$base00'"
bold_color="'$base05'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
