#!/bin/bash

# Base 16 eighties dark colors for gnome-terminal 3.10

base00=#2d2d2d
base01=#393939
base02=#515151
base03=#747369
base04=#a09f93
base05=#d3d0c8
base06=#e8e6df
base07=#f2f0ec
base08=#f2777a
base09=#f99157
base0A=#ffcc66
base0B=#99cc99
base0C=#66cccc
base0D=#6699cc
base0E=#cc99cc
base0F=#d27b53

palette="['$base00','$base08','$base0B','$base0A','$base0D','$base0E','$base0C','$base05','$base03','$base09','$base01','$base02','$base04','$base06','$base0F','$base07']"
foreground_color="'$base05'"
background_color="'$base00'"
bold_color="'$base05'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
