#!/bin/bash

# Base 16 solarized light colors for gnome-terminal 3.8.x

base00=#002b36
base01=#073642
base02=#586e75
base03=#657b83
base04=#839496
base05=#93a1a1
base06=#eee8d5
base07=#fdf6e3
base08=#dc322f
base09=#cb4b16
base0A=#b58900
base0B=#859900
base0C=#2aa198
base0D=#268bd2
base0E=#6c71c4
base0F=#d33682

palette="['$base01','$base08','$base0B','$base0A','$base0D','$base0F','$base0C','$base06','$base00','$base09','$base02','$base03','$base04','$base0E','$base05','$base07']"
foreground_color="'$base02'"
background_color="'$base07'"
bold_color="'$base02'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
