#!/bin/bash

# Base 16 chalk dark colors for gnome-terminal 3.8.x

base00=#151515
base01=#202020
base02=#303030
base03=#505050
base04=#b0b0b0
base05=#d0d0d0
base06=#e0e0e0
base07=#f5f5f5
base08=#fb9fb1
base09=#eda987
base0A=#ddb26f
base0B=#acc267
base0C=#12cfc0
base0D=#6fc2ef
base0E=#e1a3ee
base0F=#deaf8f

palette="['$base00','$base08','$base0B','$base0A','$base0D','$base0E','$base0C','$base05','$base03','$base09','$base01','$base02','$base04','$base06','$base0F','$base07']"
foreground_color="'$base05'"
background_color="'$base00'"
bold_color="'$base05'"

dconfdir=/org/gnome/terminal/legacy/profiles:
profile_id=$(dconf list /org/gnome/terminal/legacy/profiles:/ | sed -e 's/\///g' -n -e '1p')
profile_path=$dconfdir/$profile_id

# color palette
dconf write $profile_path/palette $palette

# foreground, background and highlight color
dconf write $profile_path/foreground-color $foreground_color
dconf write $profile_path/background-color $background_color
dconf write $profile_path/bold-color $bold_color

# profile does not use theme colors
dconf write $profile_path/use-theme-colors "false"

# highlighted color different from foreground color
dconf write $profile_path/bold-color-same-as-fg "false"
